// import React, { useState, useEffect } from 'react'
// import './loginButton.style.css'
// import { useNavigate } from 'react-router-dom'
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
// import { faUser } from '@fortawesome/free-solid-svg-icons'
// import axios from 'axios'
// import { LogoutApi, localhostLogout } from '../../constants/ApiList'